import type { Metadata } from "next";
import { Zen_Old_Mincho, Arizonia } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const zenOldMincho = Zen_Old_Mincho({
  weight: ["400"], // 必要なウェイトを指定 (例: 400, 700)
  subsets: ["latin"], // 必要なサブセットを指定 (通常は 'latin')
  display: "swap", // フォント読み込み中の挙動
  variable: "--font-zen-old-mincho", // CSS変数として利用する場合 (任意)
});

const arizonia = Arizonia({
  weight: ["400"], // 必要なウェイトを指定
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arizonia", // CSS変数として利用する場合 (任意)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${zenOldMincho.variable} ${arizonia.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
